apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-tpgccli
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ms-tpgccli
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60